### ISSUE TITLE
Неможливо вибрати текст в новині

### ISSUE THREAD

**Issue by TeTaApp** [TeTaApp/School-3D#1]

**Comment by lexvyshnevskyy** [comment]
новина фотографії зі свята
 фотка є
+ ссиль не паше( описав окремим багом)
+в длоці опис новини зявляється скролінг ( хоча в мене лопатофон великий)

заскрінив

**Comment by lexvyshnevskyy** [comment]
http://test40.deecoone.com.ua/issue2

**Comment by TeTaApp** [comment]
додано можливість переходу по лінці
