### ISSUE TITLE
Кнопка "Замовити" меню з головної сторінки навігує на неправильний скрін

### ISSUE THREAD

**Issue by ylysov** [TeTaApp/School-3D#11]
На головній сторінці в розділі Меню можна побачити на який найближчий день не замовлене меню.
<img width="375" alt="13 09 18 13 37 25" src="https://user-images.githubusercontent.com/15998282/45483803-4f462b00-b752-11e8-82ea-4b5fd1586012.png">

Я бачу, що не замовлено на 18 вересня, порожніх днів 4 і пропозиція "Замовити".

Коли натиснути на "Замовити" - навігує на огляд меню поточного тижня:
![13 09 18 13 37 35](https://user-images.githubusercontent.com/15998282/45483888-90d6d600-b752-11e8-9739-f5c68b503c8b.png)

Очікувана поведінка:
Замовити навігує на перший незаповнений день в режимі едітора:
![13 09 18 13 37 58](https://user-images.githubusercontent.com/15998282/45483924-ab10b400-b752-11e8-8b7e-bc20181fface.png)

Пристрій iPhone 8, iOS 11.2.2, версія аплікації 1.5

**Comment by TeTaApp** [comment]
Буде додано у версії 1.7.

**Comment by TeTaApp** [comment]
Виправлено у версії 1.9
