### ISSUE TITLE
Повідомлення - відправник дитина чи батьки

### ISSUE THREAD

**Issue by ylysov** [TeTaApp/School-3D#12]
Не впевнена чи бага, але для мене неочікувана поведінка.
До 1го аккаунту дитини зареєстровано 2 аккаунти батьків. На головній сторінці все ок - я бачу своє імя.
На сторінці повідомлень - імя дитини.
І я і чоловік бачимо ідентичну історію повідомлень, хоча всі повідомлення були відправлені мною.

Питання перше - повідомлення належать до аккаунта дитини чи до аккаунта батьків?
Друге - якщо це ок, що двоє батьків бачать ідентичну переписку, то було б дуже добре хоча б ідентифікувати відправника, щоб не плутатись хто відправив повідомлення з мого аккаунта.

![25 09 18 22 58 08](https://user-images.githubusercontent.com/15998282/46065070-cda2c400-c179-11e8-903c-086c13d530ba.png)

**Comment by TeTaApp** [comment]
Відправник - дитина. Це зроблено для того щоб вчителі мали змогу написати батькам дитини одночасно, і не путались в прізвищах(може бути що в батьків різні прізвища). Тому все вірно, Ви обоє бачите однакові повідомлення.

**Comment by ylysov** [comment]
Було б добре покращити юай в повідомленнях.  Коли вибрано чат з переглядом повідомлень, то ще можна зрозуміти які повідомлення вхідні, які вихідні. Коли ж вибрати перегляд конкретного повідомлення - нема різниці між вхідними і надісланими повідомленнями.
<img width="375" alt="01 10 18 09 21 39" src="https://user-images.githubusercontent.com/15998282/46272909-88a0d800-c553-11e8-9b90-da23faaddc65.png">
<img width="375" alt="01 10 18 09 21 53" src="https://user-images.githubusercontent.com/15998282/46272910-88a0d800-c553-11e8-9f28-f2aee19839a7.png">

І все-таки було б дуже добре в надісланих повідомленнях бачити хто саме його надсилав (ім'я батьків) навіть якщо це будо відображено в тому самому чаті, який прикріплений до аккаунту дитини.

**Comment by TeTaApp** [comment]
Гаразд, добавлю в наступній версії. Відправника теж додам, дані про те хто саме відправив є.

**Comment by TeTaApp** [comment]
Додано в версії 1.8
