### ISSUE TITLE
З "Класу" зникли інші діти

### ISSUE THREAD

**Issue by vtytar** [TeTaApp/School-3D#14]
## Опис проблеми
Закладка меню "Клас" містить у переліку лише одну дитину/дітей зареєстрованого користувача. Ще декілька тижнів тому можна було побачити усіх однокласників.

![school3d_incomplete_class](https://user-images.githubusercontent.com/10366436/46921347-d95c0a80-d002-11e8-9d87-c906312baf9f.jpg)

## Платформа
iOS

## Варіанти розв'язку
- якщо це вада, повернути однокласників у список
- якщо інших дітей не показано навмисно (наприклад, через конфіденційність), додати відповідне повідомлення

**Comment by TeTaApp** [comment]
Вже зафіксано, буде в новій версії.

**Comment by vtytar** [comment]
Дякую, чекаємо вихід 1.8.

**Comment by TeTaApp** [comment]
Виправлено в версії 1.8

**Comment by vtytar** [comment]
Перевірив, дійсно виправлено. Дякую.
