### ISSUE TITLE
Не відправляється(або не відображається як відправлене) повідомлення Адміністратору

### ISSUE THREAD

**Issue by ylysov** [TeTaApp/School-3D#15]
Отримувач - Адміністратор
Відправник - Лисович Юлія

попередня історія повідомлень: 14 отримано, 18 надіслано.
Останнє повідомлення яке відображається в цьому чаті  надіслане Адміністратором 19 жовтня.
1 листопада відправляю повідомлення до Адміністратора - після спінера нотифікація що відіслано - але в чаті відправлене повідомлення не відобразилось, кількість надісланих не зрослаю
Спробувала 2 рази надіслати до Адміністатора - така сама поведінка - не зявилось в чаті.

Спробувала відправити повідомлення отримувачу Test Teacher - відправилось і відображається в чаті. Але це новий чат.

**Comment by TeTaApp** [comment]
Можете повідомити яка у вас версія програми? Чи відтворюється досі помилка?

**Comment by ylysov** [comment]
Щойно перевірила - вже не відтворюється.
Зараз версія 1.8
