### ISSUE TITLE
На головній сторінці відображається старе повідомлення

### ISSUE THREAD

**Issue by ylysov** [TeTaApp/School-3D#16]
На головній сторінці в секції повідомлення, відображається старе вхідне повідомлення від адімістратора (за 9 жовтня)
![01 11 18 10 20 03](https://user-images.githubusercontent.com/15998282/47841016-7a471580-ddb8-11e8-8c13-0b19ba0758f9.png)
після цього повідомлення в мене вже є новіші отримані від Адміністратора (19 жовтня), а також повідомлення отримані від ментора (17 жовтня)
![01 11 18 10 20 24](https://user-images.githubusercontent.com/15998282/47841017-7a471580-ddb8-11e8-869b-999615e1af21.png)

Очікуваний результат: на головній сторінці завжди відображається останнє вхідне повідомлення, незалежно від віправника

**Comment by TeTaApp** [comment]
В наступній версії виправимо цю помилку.

**Comment by TeTaApp** [comment]
Виправлено у версії 1.9
