### ISSUE TITLE
Upload all photos automatically to Google Photos

### ISSUE THREAD

**Issue by AndrewDreamer** [TeTaApp/School-3D#17]
Звичайно дякуємо за можливість переглядати фото в додатку проте було б неймовірно круто якщо б усі фото автоматично завантажувались в гугл фото - адже там є безлімітний план + якщо б це відбувалось по класах і попредметно - батьки б змогли підписуватись на альбом, наприклад, "Англійська. 1-Б" і в один клік додавати фото своєї дитини собі в альбом. 
Це була б просто кіллер фічя! :)

**Comment by TeTaApp** [comment]
У версії 1.10 з'явилась можливість зберігати фото або ділитись ним. Це дозволяє закинути фото на гугл або куди-інде. Щодо автоматичного завантажування на гугл - подумаємо пізніше..

**Comment by AndrewDreamer** [comment]
Супер! Дякую за можливість збільшити і зберегти фото!

**Comment by TeTaApp** [comment]
На жаль не бачу можливості організувати фото на гугл. Гугл дозволяє створювати альбоми з фото, але не дозволяє додавати вкладені папки - https://support.google.com/photos/thread/134366?hl=en
На жаль неможливо створити структуру: Школа/Клас/Предмет/Дата/Фото або хоча б Школа/Клас/Предмет/Фото. А підтримувати лише альбоми з назвами "Школа 3D - 2018/2019 - Клас 2 - Математика" буде важко..
