### ISSUE TITLE
Спрацьовування меню\підменю\показ контенту

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#2]
Спрацьовування меню\підменю\показ контенту коливається від 100мс до 7000 мс

баг легко повторюється - зайшли наприклад в переписку, почикали 30-60 секеунд(або блок\анблок телефону) і наступний контент прилітаєє з диким запізненням

мені виглядає що певно пріложуха має відкритий коннект\сокет....

**Comment by lexvyshnevskyy** [comment]
знову зойно хапнув баг з менюхою

вимкнутий апарат -вмикнули і відкрили апку - показало хедер і... чекаєм є контент- натискаєм на значок меню - меню не показує.
пробую свайпом меню вилазить
за 9 секунд меню почало працювати на кнопку

**Comment by TeTaApp** [comment]
потестую ще потім, але поки не замічав такого. хіба на повільному інтернеті.
Наразі на телефоні нічого не кешується, всі дані оновлюються з сервера. в майбутньому буде добавлено кешування, і довантаження даних в бекграунді.

**Comment by lexvyshnevskyy** [comment]
kydaju v okremu papku ranishni bugs(fotky vid ranku seredy)
http://test40.deecoone.com.ua/issue2

**Comment by TeTaApp** [comment]
прошу оновити програму і глянути як зараз все працює

**Comment by lexvyshnevskyy** [comment]
зі швидкодією покращилось суттєво.

виліз ще олин баг/фіча
1. вийшов з зони покриття вайфай 
2. пріложуха зааисла
3. гугл запропонував вимкнути і написати відгук
4. пріложуха відповіла
5. гугл всеодно бачив її як залиплу прогу

може при втраті звязку вартує ставити або реконект або повідомлення (так як в онлайн іграх)

заняло то секунд 30
