### ISSUE TITLE
Регулярно вилоговує з аплікації

### ISSUE THREAD

**Issue by AndrewDreamer** [TeTaApp/School-3D#20]
На дружини мобільному може бути успішно залогований і вона далі може користуватись, проте мене викидує десь кожні 2 тижні.

**Comment by TeTaApp** [comment]
Можете пояснити що значить викидує?
Вилоговує - потрібно знову залоговуватись? чи викидає помилку?

**Comment by AndrewDreamer** [comment]
Так, вилоговує і потрібно ще раз залоговуватись

**Comment by AndrewDreamer** [comment]
Останнім часом десь двічі в тиждень вилоговує - оскільки треба чекати вечора, бо залоговано креденшелами дружини - це реально дуже не зручно.

**Comment by TeTaApp** [comment]
Можете надати ще додатково інформацію?
1. Це остання версія 1.15.1?
2. Це стається при відкритті аплікації з пуш меседжа чи звичайному відкритті?
3. У дружини на телефоні теж викидує?
4. На мобільному у вас достатньо місця?

**Comment by TeTaApp** [comment]
Також не обов'язково використовувати одного користувача. До дитини можна додати кілька батьків.

**Comment by AndrewDreamer** [comment]
1. так, це остання версія 
2. зазвичай - я бачу, що або не оновляються дані або якось зависає намертво як вчора-сьогодні і тоді кіляю з пам'яті і все
3. ні зазвичай не викидує (в неї правда натівний Андроїд і теж 6й), правда сьогодні викинуло і її
4. звичайно :) напевне 10 ГБ

Я так бачу, що прийдеться завести ще оддного юзера, просто всі повідомлення втратяться.

**Comment by TeTaApp** [comment]
Дякую за відповіді.
Повідомлення не втратяться, вони прикріплені до дитини а не до батька.
Обоє батьків бачать ті самі повідомлення, і можуть обоє писати від дитини(чи дітей якщо є кілька).

**Comment by AndrewDreamer** [comment]
Це супер! Здається на початку такої можливості не було! Дякую!

**Comment by TeTaApp** [comment]
Така можливість була додана десь з листопада.
Можете помоніторити ситуацію з вилоговуваннями? У версії 1.15.13 було додано зміни які мали б це змінити.

**Comment by AndrewDreamer** [comment]
Так, звичайно - я вже оновився і залогований під своїм акаунтом. 
На що звертати увагу? Бо в мене немає однозначного воркфлову коли воно вилоговує

**Comment by TeTaApp** [comment]
Прошу повідомити коли наступного разу вилогує, буду шукати причину в логах.

**Comment by TeTaApp** [comment]
Як там з вилоговуванням? Можна закривати цю проблему?

**Comment by AndrewDreamer** [comment]
З того часу ще не вилоговувало. Виглядає, що все добре.

**Comment by TeTaApp** [comment]
дякую за відповідь!
