### ISSUE TITLE
Довгі теми обрізає часто на Андроїді 6

### ISSUE THREAD

**Issue by AndrewDreamer** [TeTaApp/School-3D#21]

**Comment by AndrewDreamer** [comment]
![photo_2019-01-31_14-58-03](https://user-images.githubusercontent.com/45007584/52055665-b1b89000-2568-11e9-9fd0-bf77a2cea698.jpg)

**Comment by TeTaApp** [comment]
ок, в наступній версії зміню.

**Comment by TeTaApp** [comment]
Можете глянути після оновлення 1.15.13?

**Comment by AndrewDreamer** [comment]
Так, здається навіть старі теми пофіксались. Дякую

**Comment by TeTaApp** [comment]
Так, з старими темами все в порядку. Дякую за повідомлення про помилку!
