### ISSUE TITLE
Пуш повідомлення новин приходять декілька разів

### ISSUE THREAD

**Issue by AndrewDreamer** [TeTaApp/School-3D#22]
![photo_2019-02-13_12-41-39](https://user-images.githubusercontent.com/45007584/52705909-bb8cbb00-2f8c-11e9-878c-96f3e3b40c4c.jpg)

Останнім часом це майже стабільно, що на новину приходить 4 пуш повідомлення. 
Версія 1.15.16, Андроїд 6.0

**Comment by TeTaApp** [comment]
Так, була така проблема у людей які спочатку заходили під одним користувачем, а потім отримавши окремий доступ під іншим. На телефони приходили подвоєння (але саме цю новину адміністрація вислала помилково два рази, тому прийшло подвійне подвоєння).
Вже помилка виправлена на сервері.
