### ISSUE TITLE
Інформаційні блоки що містять урли

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#3]
Інформаційні блоки що містять урли - урли не клікабельні.
перевірити можна в новинах та перепистці

**Comment by TeTaApp** [comment]
буде пофіксано в наступній версії

**Comment by lexvyshnevskyy** [comment]
ok

**Comment by TeTaApp** [comment]
має бути ок в новій версії

**Comment by lexvyshnevskyy** [comment]
для дроїда все добре.
