### ISSUE TITLE
Вкладка огляд меню

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#4]
вкладка огляд меню.
календар - випадачка не працюючий, або на нього діє попередня бага з затримкою відповідію зараз довантавжу скрін

**Comment by lexvyshnevskyy** [comment]
+ тодоткова штука. натискаєш на трикутничок зліва і показхує попередній проміжок часу..... якого нема...
+ олівчик редагування меню - спрацював з восьмого разу -Ю дивись багу попередню з затримкою
+ в датах в минулому у скріні відображення замовлень хавки пріложуха просто монструозно підвисає(10+ секунд на відображення).....

+юї просто жах. переробіть. реально тяжко. як варіант вартує зробити підсвічення цілого поля іншим кольором. типу чекнули. щоб для навіть блонди було зрозуміло як то зробити

+ немає можливості замовити хавку на наступні2+ дня

+ вартує зробити попап на підтвердження, або інформативне повідомлення що данні збережено

**Comment by lexvyshnevskyy** [comment]
головна сторінка - повідомлення що є не замовлений день і можливість перейти у вкладку меню. тиць по повідомленню - ми у меню хавки. є замовлення на сьогодні, завтора. ок тицяєм олівчик і.... і нічого. тицяю 30 секунд і нічого... иає бути набір повідомлень на будьякий вирадок

+ юї треш

**Comment by TeTaApp** [comment]
1) на якій операційній системі ви тестуєте? яка версія?
2) що за календар-випадачка на огляді меню?
3) попередній проміжок якого нема - зроблю пізніше окремий баг на то (приберу незаповнені проміжки з усіх сторінок)
4) щодо затримок - помічаю їх лише з поганим зв'язком
5) вибрані пункти меню - зміню колір
6) немає можливості замовити на наступні 2+ дні - це на які дні? сьогодні (в середу, до 15) є можливість замовити на четвер і пятницю.
7) інформативні повідомлення про збереження даних добавлю.

**Comment by lexvyshnevskyy** [comment]
1. droid 7.0+.... zranku potestuju na ios
2. zaraz zroblu skrin+ jak by yogo popravyty dla ui
oooo scojno pobachyv fix. 
http://test40.deecoone.com.ua/issue 4.2/
3. ok
4. na wifi, 3-4g. mozlyvo navantazenna  na serveri (mav sogodni take, google zavitav v gosti)
5.ok
6. kladu skriny vid ranku
http://test40.deecoone.com.ua/issue 4.7/
na 23:48 pracuje vse normalno i shvydko
7.ok
