### ISSUE TITLE
Проблеми години

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#5]
відображає годину публікації не в gmt+2

**Comment by lexvyshnevskyy** [comment]
пригадав як на своїй гібридній правив то.
найкразе дієвіший варіант виставляти час зі сторони сервера .
якзо його правити на стороні апарату то толку не буде. бо є багато апаратів в котрих час прописаний на країну виробника.
приклад у користувача в системі стоїть+2 а жаба бачить -8 китай і нічого не вдієш

**Comment by TeTaApp** [comment]
![image](https://user-images.githubusercontent.com/42968857/45088590-200c3a00-b112-11e8-8a2b-462c18836f44.png)
щойно спробував, надсилає в годині школи.

**Comment by TeTaApp** [comment]
деплой фікса відбувся вночі з 4 на 5 вересня, всі новостворені часи мають бути в часовій таймзоні школи.

**Comment by lexvyshnevskyy** [comment]
ok. mozna todi cej zakryvaty
