### ISSUE TITLE
розклад. порожній на цей момент

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#6]
не знаю чи бага, але на 8:30 середи розклад порожній

+ та сама бага з календарем

**Comment by TeTaApp** [comment]
тільки на 8-30 порожній чи весь день? розклад в процесі наповнення, до кінця тижня має бути в кожного класу.

**Comment by lexvyshnevskyy** [comment]
http://test40.deecoone.com.ua/issue6_android
scojno zrobyv skriny
