### ISSUE TITLE
гуртки

### ISSUE THREAD

**Issue by lexvyshnevskyy** [TeTaApp/School-3D#7]
все норм окрім баги з календарем

**Comment by lexvyshnevskyy** [comment]
ем. виглядає що гуртки мали б вибиратися?

**Comment by TeTaApp** [comment]
це лише режим перегляду всіх можливих гуртків (принаймні поки що), для ознайомлення.

**Comment by lexvyshnevskyy** [comment]
ok todi vidkladem na potim

**Comment by TeTaApp** [comment]
додано вибір гуртків
