### ISSUE TITLE
Нотіфікейшин про Повідомлення замість превью мітить код

### ISSUE THREAD

**Issue by ylysov** [TeTaApp/School-3D#9]
Нотіфікейшин на залоканому скріні показав ось таке, заміть превью повідомлення

![13 09 18 11 01 47](https://user-images.githubusercontent.com/15998282/45475510-ebfdce00-b73c-11e8-8d67-d43c905bc646.png)
![13 09 18 11 02 14](https://user-images.githubusercontent.com/15998282/45475514-ee602800-b73c-11e8-87e7-3449736fb4e4.png)

Пристрій iPhone 8, iOS 11.2.2, версія аплікації 1.5

**Comment by TeTaApp** [comment]
Сьогодні в обід закинуто оновлення на сервер. Повідомлення що містили більше 50 символі відображались невірно.
